#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nginx
"

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages."
git clone --depth=50 --branch=master https://tt-rss.org/git/tt-rss.git /opt/tt-rss/www
git clone https://github.com/m42e/ttrss_plugin-feediron.git /opt/tt-rss/feediron
git clone https://github.com/levito/tt-rss-feedly-theme.git /opt/tt-rss/feedly_theme

ln -s /opt/tt-rss/feediron /opt/tt-rss/www/plugins/feediron
ln -s /opt/tt-rss/feedly_theme/feedly /opt/tt-rss/www/themes
ln -s /opt/tt-rss/feedly_theme/feedly.css /opt/tt-rss/www/themes

chown -R www:www /opt/tt-rss/www/cache
chown -R www:www /opt/tt-rss/www/feed-icons
chown -R www:www /opt/tt-rss/www/lock

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
